### ISSUE TITLE
ValueError: IV must be 16 bytes long

### ISSUE THREAD

**Issue by najashark** [cyberinc/cloacked-pixel#1]
i have no problem with hide and analyse option, but when try to extract it says ValueError: IV must be 16 bytes long

r0x@b0x:~/Desktop/C11/cloacked-pixel$ python lsb.py extract ../wgmy_03_x.bmp out 12345
[+] Image size: 1024x622 pixels.
Traceback (most recent call last):
  File "lsb.py", line 194, in <module>
    extract(sys.argv[2], sys.argv[3], sys.argv[4])
  File "lsb.py", line 123, in extract
    data_dec = cipher.decrypt(data_out)
  File "/home/r0x/Desktop/C11/cloacked-pixel/crypt.py", line 23, in decrypt
    cipher = AES.new(self.key, AES.MODE_CBC, iv)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long

**Comment by Twinters007** [comment]
https://github.com/cyberinc/cloacked-pixel/blob/master/crypt.py#L12

This needs to change to 16

**Comment by Mod233** [comment]
u can debug the "lsb.py", line 115: data_out = assemble(v),  it obviously that function assemble() made a big mistake.

**Comment by Zciurus-Alt-Del** [comment]
I may be a little bit late to the party, but I am also having this problem and there's no solution yet.

**Comment by Evanescent-dm** [comment]
You need to use .png images instead of .jpg images

**Comment by rakeshsivaji** [comment]
@najashark  did you find the solution, I am also getting the same error while decrypting
